// ─────────────────────────────────────────────────────────────────────────────
// DESIGN INDEX — Resource Data
// ─────────────────────────────────────────────────────────────────────────────
// ADD a resource  → copy any entry, give it a unique id, fill in the fields.
// FEATURE a card  → set  featured: true  (keep ≤ 5 at once).
// MARK as new     → set  added: 'YYYY-MM-DD'  (shows NEW badge for 30 days).
// ADD thumbnail   → drop  images/{id}.jpg  into the images/ folder. No code changes needed.
// ─────────────────────────────────────────────────────────────────────────────

const CATEGORIES = [
  { id: 'design-inspo',     label: 'Inspo',             badge: 'INSPO', emoji: '⚡' },
  { id: 'type-tools',       label: 'Type Tools',        badge: 'TYPE',  emoji: '🛠️' },
  { id: 'type-marketplace', label: 'Type Shops',        badge: 'MKT',   emoji: '🌐' },
  { id: 'type-foundry',     label: 'Type Foundries',    badge: 'FNDR',  emoji: '🔤' },
  { id: 'assets',           label: 'Assets',            badge: 'KIT',   emoji: '🧰' },
  { id: 'color',            label: 'Color',             badge: 'HUE',   emoji: '🖍️' },
  { id: 'stock',            label: 'Stock',             badge: 'IMG',   emoji: '🖼️' },
  { id: 'design-news',      label: 'News',              badge: 'EDIT',  emoji: '🧠' },
  { id: 'books-titles',     label: 'Books',             badge: 'READ',  emoji: '📚' },
  { id: 'bookstores',       label: 'Bookstores',        badge: 'SHOP',  emoji: '🛒' },
  { id: 'creators',         label: 'Creators',          badge: 'WATCH', emoji: '🎥' },
  { id: 'agency-studio',    label: 'Studios',           badge: 'AGCY',  emoji: '🏢' },
  { id: 'designers',        label: 'Designers',         badge: 'DSGN',  emoji: '🎨' },
];

const RESOURCES = [

  // ── DESIGN INSPO ──────────────────────────────────────────────────────────
  { id: 'visuelle',        name: 'Visuelle',         url: 'https://visuelle.co.uk/?_sft_category=design',        category: 'design-inspo', desc: 'Motto: "if it\'s great, it goes on." - Highly curated beyond design since 2007',               tags: ['editorial', 'identity'],       image: null, featured: false, added: '2026-04-27' },
  { id: 'visual-journal',  name: 'Visual Journal',   url: 'https://visualjournal.it',                            category: 'design-inspo', desc: 'All the top branding projects curated by an AD in Italy',            tags: ['branding', 'curated'],         image: null, featured: false, added: '2026-04-27' },
  { id: 'arena',           name: 'Are.na',           url: 'https://www.are.na',                                  category: 'design-inspo', desc: 'Where you find the most experimental, original, innovative work online',     tags: ['bookmarking', 'moodboards'],   image: null, featured: false },
  { id: 'behance',         name: 'Behance',          url: 'https://www.behance.net/',                            category: 'design-inspo', desc: 'Because it\'s a portfolio site, the case studies are worth scrolling',    tags: ['portfolio', 'inspiration'],    image: null, featured: false },
  { id: 'cosmos',          name: 'Cosmos',           url: 'https://cosmos.so',                                   category: 'design-inspo', desc: 'Search inspo by hex code. A step up from Pinterest in curation',             tags: ['curated', 'editorial'],        image: null, featured: false },
  { id: 'pinterest',       name: 'Pinterest (@matthewcrtv)', url: 'https://www.pinterest.com/matthewcrtv/_saved/',        category: 'design-inspo', desc: 'My board of 2600+ pins organized by type, layout, branding, color, etc.',                tags: ['reference', 'moodboards'],     image: null, featured: false },
  { id: 'archives-design', name: 'Archives Design',  url: 'https://archives.design',                             category: 'design-inspo', desc: 'Click the book then "see it on archive.org" and flip through the entire scan',           tags: ['archive', 'historical'],       image: null, featured: false },
  { id: 'savee-it',        name: 'Savee It',         url: 'https://savee.it',                                    category: 'design-inspo', desc: 'Paid inspo boards, but used by all the big names (Apple, Nike, Adobe, etc.)',            tags: ['bookmarking', 'moodboards'],   image: null, featured: false },
  { id: 'design-reviewed', name: 'Design Reviewed',  url: 'https://designreviewed.com/',                         category: 'design-inspo', desc: '10,000 pieces of design history scanned and organized by decade. Insane.',       tags: ['archive', 'historical'],       image: null, featured: false },

  // ── STOCK ─────────────────────────────────────────────────────────────────
  { id: 'artvee',                name: 'ArtVee',                url: 'https://artvee.com/',                                   category: 'stock', desc: 'Free high-res downloads of public domain art',              tags: ['fine art', 'public domain'],   image: null, featured: false },
  { id: 'public-work',           name: 'Public.Work',           url: 'https://public.work/',                                  category: 'stock', desc: 'Search engine for public domain images',                    tags: ['public domain', 'searchable'], image: null, featured: false, added: '2026-04-27' },
  { id: 'public-domain-archive', name: 'Public Domain Archive', url: 'https://pdimagearchive.org/infinite-view/',             category: 'stock', desc: 'Open collection of 11,000+ public-domain images',           tags: ['historical', 'free'],          image: null, featured: false },
  { id: 'unsplash-exp',          name: 'Unsplash Experimental', url: 'https://unsplash.com/t/experimental',                  category: 'stock', desc: 'Handpicked abstract photography collection',                tags: ['abstract', 'photography'],     image: null, featured: false },
  { id: 'pexels',                name: 'Pexels',                url: 'https://www.pexels.com/',                               category: 'stock', desc: 'Free high-quality stock photos and videos',                 tags: ['free', 'commercial'],          image: null, featured: false },

  // ── TYPE TOOLS ────────────────────────────────────────────────────────────
  { id: 'font-ninja',  name: 'Font Ninja',   url: 'https://chromewebstore.google.com/detail/fonts-ninja/eljapbgkmlngdpckoiiibecpemleclhh?hl=en-US', category: 'type-tools', desc: 'Identify any font on any website instantly. The most useful extension I own.',        tags: ['extension', 'fonts'],  image: null, featured: true, featuredOrder: 2, added: '2026-04-27' },
  { id: 'font-base',   name: 'Font Base',    url: 'https://fontba.se/',                                                                              category: 'type-tools', desc: 'Amazing free features to organize fonts, pair, & discover new releases',         tags: ['fonts', 'manager'],    image: null, featured: false },
  { id: 'typelab',     name: 'TypeLab',      url: 'https://matthewcrtv.gumroad.com/l/typelab',                                                       category: 'type-tools', desc: 'My type system. 125+ curated fonts, 30 pairings, type directory, & a testing script.',                  tags: ['free', 'fonts'],       image: null, featured: false },

  // ── TYPE MARKETPLACE ──────────────────────────────────────────────────────
  { id: 'creative-market',    name: 'Creative Market',       url: 'https://creativemarket.com/fonts',                    category: 'type-marketplace', desc: 'I sort by "best selling" or "trending" to skip the 1000\'s of unnecessary fonts',       tags: ['fonts', 'marketplace'],  image: null, featured: false },
  { id: 'pixel-surplus',      name: 'Pixel Surplus',         url: 'https://pixelsurplus.com',                            category: 'type-marketplace', desc: 'The best value on the market. The type bundles are worth it alone.',             tags: ['bundles', 'fonts'],       image: null, featured: false },
  { id: 'type-department',    name: 'Type Department',       url: 'https://type-department.com',                         category: 'type-marketplace', desc: 'Indie font marketplace that\'s curated well. Leans experimental, edgy, & expressive.',                 tags: ['indie', 'marketplace'],  image: null, featured: false, added: '2026-04-27' },
  { id: 'youworkforthem-type',name: 'YouWorkForThem Fonts',  url: 'https://www.youworkforthem.com/fonts/bestselling',    category: 'type-marketplace', desc: 'When I want quality type without breaking the budget... this is where I go.',     tags: ['fonts', 'marketplace'],  image: null, featured: false, added: '2026-04-27' },

  // ── TYPE FOUNDRY ──────────────────────────────────────────────────────────
  { id: 'blaze-type',         name: 'Blaze Type',             url: 'https://blazetype.eu/',                    category: 'type-foundry', desc: 'Wide range of variable fonts. Click into each one... many with over 100 styles. Crazy.',            tags: ['display', 'foundry'],       image: null, featured: false },
  { id: 'brandon-nickerson',  name: 'Brandon Nickerson',      url: 'https://www.bnicks.com/',                  category: 'type-foundry', desc: 'Fun fact, join his email list - he releases a free font almost every week. Great selection.',                    tags: ['lettering', 'wordmarks'],   image: null, featured: false, added: '2026-04-27' },
  { id: 'emyself-design',     name: 'Emyself Design',         url: 'https://emyselfdesign.com',                category: 'type-foundry', desc: 'I find the best scripts from this studio alone. Probably own 20+ from this catalog.',                tags: ['expressive', 'display'],    image: null, featured: false },
  { id: 'off-type',           name: 'Off-type',               url: 'https://off-type.com',                     category: 'type-foundry', desc: 'Very experimental & "off-beat" fonts for pushing boundaries. Worth the scroll.',                      tags: ['variable', 'kinetic'],      image: null, featured: false, added: '2026-04-27' },
  { id: 'sharp-type',         name: 'Sharp Type',             url: 'https://www.sharptype.co/',                category: 'type-foundry', desc: 'Premium fonts that are probably out of budget. They offer trials as well.',                     tags: ['editorial', 'premium'],     image: null, featured: false },
  { id: 'ohno-type',          name: 'OhNo Type Co',           url: 'https://ohnotype.co/',                     category: 'type-foundry', desc: 'Fun and expressive display fonts that somehow stay legible.',                        tags: ['display', 'text'],          image: null, featured: false },
  { id: 'ott-foundry',        name: 'OTT Foundry',            url: 'https://ott-foundry.com/',                 category: 'type-foundry', desc: 'Their whole goal is to create unique ornamental display type for high impact',               tags: ['grotesque', 'korean'],      image: null, featured: false },
  { id: 'pangram-pangram',    name: 'Pangram Pangram',        url: 'https://pangrampangram.com',               category: 'type-foundry', desc: 'My #1 type foundry. All their fonts are bangers. All have trials. Thank me later.',                      tags: ['free', 'branding'],         image: null, featured: false },
  { id: 'tan-type',           name: 'Tan Type Co',            url: 'https://creativemarket.com/tantype',       category: 'type-foundry', desc: 'Expressive display gold here. 100+ low cost expressive and ornate headline fonts.',                     tags: ['fashion', 'display'],       image: null, featured: false },
  { id: 'designers-foundry',  name: 'The Designers Foundry',  url: 'https://www.thedesignersfoundry.com/',    category: 'type-foundry', desc: 'They kind of do it all. From experimental and quirky to super clean. Worth scanning.',                   tags: ['indie', 'limited'],         image: null, featured: false },
  { id: 'tropical-type',      name: 'Tropical Type',          url: 'https://tropicaltype.com',                 category: 'type-foundry', desc: 'I like their mission - make low cost single weight expressive display fonts. That\'s it.',                        tags: ['display', 'apparel'],       image: null, featured: false },
  { id: 'abc-dinamo',         name: 'ABC Dinamo',             url: 'https://abcdinamo.com/',                   category: 'type-foundry', desc: 'They give you free early access to complete but unpublished fonts. Fun to play with.',                   tags: ['variable', 'swiss'],        image: null, featured: false },
  { id: 'vj-type',            name: 'VJ Type',                url: 'https://www.vj-type.com',                  category: 'type-foundry', desc: 'Hover to see them in action. Type that\'s both expressive & elegant... but premium price tag.',                tags: ['variable', 'open-source'],  image: null, featured: false },

  // ── DESIGN NEWS ───────────────────────────────────────────────────────────
  { id: 'brand-new',          name: 'Brand New',          url: 'https://www.underconsideration.com/brandnew',  category: 'design-news', desc: 'Daily critiques of new logos and identity work',         tags: ['logos', 'critiques'],    image: null, featured: false },
  { id: 'creative-boom',      name: 'Creative Boom',      url: 'https://www.creativeboom.com/',                category: 'design-news', desc: 'Design news, inspiration, and interviews',               tags: ['editorial', 'advice'],   image: null, featured: false },
  { id: 'its-nice-that',      name: "It's Nice That",     url: 'https://www.itsnicethat.com/',                 category: 'design-news', desc: 'Art and design culture blog',                           tags: ['editorial', 'culture'],  image: null, featured: false },
  { id: 'tldr-design',        name: 'TLDR Design',        url: 'https://tldr.tech/design',                     category: 'design-news', desc: 'Weekly design news and inspiration',                    tags: ['newsletter', 'weekly'],  image: null, featured: true, featuredOrder: 4, added: '2026-04-22' },
  { id: 'the-brand-identity', name: 'The Brand Identity', url: 'https://the-brandidentity.com/',               category: 'design-news', desc: 'Brand identity and print case studies',                 tags: ['identity', 'editorial'], image: null, featured: false },

  // ── YOUTUBE CREATORS ──────────────────────────────────────────────────────
  { id: 'design-syndrome-yt', name: 'Design.Syndrome',  url: 'https://www.youtube.com/@design.syndrome',  category: 'creators', desc: 'Creative studio tutorials and asset packs',           tags: ['tutorials', 'assets'],      image: null, featured: false },
  { id: 'doron-studio-yt',    name: 'Doron Studio',     url: 'https://www.youtube.com/@DoronStudio',      category: 'creators', desc: 'Photoshop and illustration tutorials',                tags: ['tutorials', 'photoshop'],   image: null, featured: false },
  { id: 'oren-meets-world',   name: 'Oren Meets World', url: 'https://www.youtube.com/@orenmeetsworld',   category: 'creators', desc: 'Freelance design vlogs and advice',                   tags: ['freelance', 'career'],      image: null, featured: false },
  { id: 'piximperfect',       name: 'PiXimperfect',     url: 'https://www.youtube.com/c/PiXimperfect',   category: 'creators', desc: 'Advanced Photoshop retouching tutorials',             tags: ['photoshop', 'tutorials'],   image: null, featured: false },
  { id: 'louis-moss',         name: 'Louis Moss',       url: 'https://www.youtube.com/@LouisMoss',       category: 'creators', desc: 'Concise Illustrator tutorials for logo & type',       tags: ['illustrator', 'tutorials'], image: null, featured: false, added: '2026-04-27' },
  { id: 'the-futur',          name: 'The Futur',        url: 'https://www.youtube.com/@thefutur',        category: 'creators', desc: 'Creative business and branding strategy advice',      tags: ['career', 'business'],       image: null, featured: false },

  // ── BOOKS ─────────────────────────────────────────────────────────────────
  { id: 'gd-visionaries', name: 'Graphic Design Visionaries',       url: 'https://www.goodreads.com/book/show/23197685-graphic-design-visionaries?ref=nav_sb_ss_1_45',         category: 'books-titles', desc: 'Profiles of 75 influential graphic designers',         tags: ['designers', 'history'],    image: null, featured: false, added: '2026-04-27' },
  { id: 'grid-systems',   name: 'Grid Systems in Graphic Design',   url: 'https://www.goodreads.com/book/show/60664913-grid-systems-in-graphic-design?utm_source=chatgpt.com', category: 'books-titles', desc: 'Classic text on grid and layout design',               tags: ['grids', 'swiss'],          image: null, featured: false },
  { id: 'herding-tigers', name: 'Herding Tigers',                   url: 'https://www.goodreads.com/book/show/34427197-herding-tigers?ref=nav_sb_ss_1_11',                    category: 'books-titles', desc: 'Creative leadership guide for team managers',          tags: ['management', 'leadership'],image: null, featured: false },
  { id: 'meggs-history',  name: "Megg's History of Graphic Design", url: 'https://www.goodreads.com/book/show/641593.Meggs_History_of_Graphic_Design?utm_source=chatgpt.com', category: 'books-titles', desc: 'Definitive history of graphic design',                 tags: ['history', 'reference'],    image: null, featured: false },
  { id: 'gd-history-2',   name: 'History of Graphic Design Vol. 2',url: 'https://www.goodreads.com/book/show/42111600-the-history-of-graphic-design-vol-2-1960-today?ref=nav_sb_ss_2_29',  category: 'books-titles', desc: 'Graphic design history: 1960 to today',  tags: ['history', 'reference'],    image: null, featured: false },
  { id: 'gd-history-1',   name: 'History of Graphic Design Vol. 1',url: 'https://www.goodreads.com/book/show/37852859-the-history-of-graphic-design-vol-1-1890-1959?ref=nav_sb_ss_1_29',   category: 'books-titles', desc: 'Graphic design history: 1890–1959',              tags: ['history', 'reference'],    image: null, featured: false },

  // ── BOOKSTORES ────────────────────────────────────────────────────────────
  { id: 'counter-print', name: 'Counter Print UK', url: 'https://www.counter-print.co.uk',  category: 'bookstores', desc: 'Modern design books, zines, and mags',               tags: ['indie', 'zines'],          image: null, featured: false },
  { id: 'draw-down',     name: 'Draw-Down Books',  url: 'https://www.draw-down.com',         category: 'bookstores', desc: 'Typography and risograph art books',                 tags: ['typography', 'risograph'], image: null, featured: false },
  { id: 'taschen',       name: 'TASCHEN',           url: 'https://www.taschen.com',           category: 'bookstores', desc: 'Coffee-table art and design books',                  tags: ['monographs', 'art'],       image: null, featured: false },
  { id: 'unit-editions', name: 'Unit Editions',    url: 'https://uniteditions.com/',         category: 'bookstores', desc: 'Limited-edition books by top designers',             tags: ['limited', 'premium'],      image: null, featured: false },
  { id: 'victionary',    name: 'Victionary',        url: 'https://victionary.com',            category: 'bookstores', desc: 'Trend-forward art and design books',                 tags: ['art books', 'asia'],       image: null, featured: false, added: '2026-04-27' },

  // ── ASSETS / RESOURCES ────────────────────────────────────────────────────
  { id: 'tooooools',           name: 'Tooooools',            url: 'https://www.tooooools.app/',                        category: 'assets', desc: 'Free lo-fi image filters',                          tags: ['free', 'effects'],        image: null, featured: false },
  { id: 'effect-app',          name: 'Effect App',           url: 'https://effect.app',                                category: 'assets', desc: 'Experimental browser image effect tool',            tags: ['effects', 'tools'],       image: null, featured: false, added: '2026-04-27' },
  { id: 'blkmarket',           name: 'BlkMarket',            url: 'https://blkmarket.com/',                            category: 'assets', desc: 'Premium textures and 3D elements for posters',      tags: ['textures', '3d'],         image: null, featured: false },
  { id: 'bracken-design',      name: 'Bracken.design',       url: 'https://www.bracken.design/',                       category: 'assets', desc: 'Grunge brushes and paper mockup elements',          tags: ['grunge', 'brushes'],      image: null, featured: false },
  { id: 'foxrockettstudio',    name: 'Foxrockettstudio',     url: 'https://foxrockettstudio.com/collections/assets',  category: 'assets', desc: 'Designer asset packs (textures, brushes, etc.)',    tags: ['assets', 'kits'],         image: null, featured: false },
  { id: 'design-family-mkt',   name: 'Design Family Market', url: 'https://www.designfamilymarket.com/',               category: 'assets', desc: 'Bundles of fonts, textures, and LUTs',              tags: ['bundles', 'photoshop'],   image: null, featured: false, added: '2026-04-27' },
  { id: 'design-syndrome',     name: 'Design Syndrome',      url: 'https://designsyndrome.com/',                       category: 'assets', desc: 'Poster templates and gradient graphic kits',        tags: ['templates', 'kits'],      image: null, featured: false },
  { id: 'doron-supply',        name: 'Doron Supply',         url: 'https://doronsupply.com',                           category: 'assets', desc: 'Photo and video overlay assets',                    tags: ['overlays', 'video'],      image: null, featured: true, featuredOrder: 5 },
  { id: 'samolevsky',          name: 'Samolevsky',           url: 'https://samolevsky.com',                            category: 'assets', desc: 'Glitch textures and retro graphic kits',            tags: ['glitch', 'textures'],     image: null, featured: false, added: '2026-04-27' },
  { id: 'studio-2am',          name: 'Studio 2AM',           url: 'https://studio2am.co',                              category: 'assets', desc: 'High-res collage elements and poster templates',    tags: ['collage', 'templates'],   image: null, featured: false },
  { id: 'studio-aaa',          name: 'Studio AAA',           url: 'https://studioaaa.com',                             category: 'assets', desc: 'Cinematic mockups and dark Lightroom presets',      tags: ['mockups', 'presets'],     image: null, featured: false },
  { id: 'studio-innate',       name: 'Studio Innate',        url: 'https://shop.studioinnate.com',                     category: 'assets', desc: 'Gradients, grids, and textures for dark designs',   tags: ['gradients', 'textures'],  image: null, featured: false },
  { id: 'true-grit',           name: 'True Grit Texture Supply', url: 'https://truegrittexturesupply.com',             category: 'assets', desc: 'Distressed brushes and craft texture packs',        tags: ['textures', 'brushes'],    image: null, featured: false },
  { id: 'youworkforthem',      name: 'YouWorkForThem',       url: 'https://youworkforthem.com',                        category: 'assets', desc: 'Marketplace for fonts, graphics, and motion assets', tags: ['fonts', 'premium'],       image: null, featured: false },

  // ── COLOR ─────────────────────────────────────────────────────────────────
  { id: 'coolors',               name: 'Coolors',               url: 'https://coolors.co/',                   category: 'color', desc: 'AI-powered palette generator',                  tags: ['palette', 'generator'], image: null, featured: false },
  { id: 'color-hunt',            name: 'Color Hunt',            url: 'https://colorhunt.co/',                 category: 'color', desc: 'Community-curated color palettes',               tags: ['palette', 'community'], image: null, featured: false },
  { id: 'adobe-color',           name: 'Adobe Color',           url: 'https://color.adobe.com',               category: 'color', desc: 'Color harmonies and palette trends tool',        tags: ['adobe', 'palette'],     image: null, featured: false },
  { id: 'pigment-shape-factory', name: 'Pigment Shape Factory', url: 'https://pigment.shapefactory.co/',      category: 'color', desc: 'Generator for gradient and duotone schemes',     tags: ['gradient', 'duotone'],  image: null, featured: true, featuredOrder: 3 },
  { id: 'khroma',                name: 'Khroma',                url: 'https://www.khroma.co',                 category: 'color', desc: 'AI-powered color palette generator',             tags: ['ai', 'palette'],        image: null, featured: false, added: '2026-04-27' },

  // ── AGENCY / STUDIO ───────────────────────────────────────────────────────
  { id: 'studio-koto',     name: 'Studio Koto',       url: 'https://www.instagram.com/studiokoto/',        category: 'agency-studio', desc: 'Brand identity and culture-focused projects',             tags: ['branding', 'instagram'],    image: null, featured: true, featuredOrder: 1, added: '2026-04-22' },
  { id: 'and-walsh',       name: 'And Walsh',          url: 'https://www.instagram.com/andwalsh/',          category: 'agency-studio', desc: 'Branding campaigns and case studies by &Walsh',           tags: ['campaigns', 'instagram'],   image: null, featured: false },
  { id: 'studio-feixen',   name: 'Studio Feixen',      url: 'https://www.instagram.com/studiofeixen/',     category: 'agency-studio', desc: 'Swiss studio with playful color and motion',              tags: ['motion', 'instagram'],      image: null, featured: false },
  { id: 'the-new-company', name: 'The New Company',    url: 'https://www.instagram.com/thenewcompany/',    category: 'agency-studio', desc: 'NYC studio with minimalist identities',                   tags: ['identity', 'instagram'],    image: null, featured: false },
  { id: 'this-is-collins', name: 'This Is Collins',    url: 'https://www.instagram.com/thisiscollins/',    category: 'agency-studio', desc: 'Culture-driven rebrands and dynamic design',              tags: ['branding', 'instagram'],    image: null, featured: false },
  { id: 'wieden-kennedy',  name: 'Wieden Kennedy',     url: 'https://www.instagram.com/wiedenkennedy/',   category: 'agency-studio', desc: 'Global ad agency known for iconic campaigns',             tags: ['advertising', 'instagram'], image: null, featured: false },
  { id: 'design-studio',   name: 'Design Studio',      url: 'https://www.instagram.com/__designstudio__/',category: 'agency-studio', desc: 'London studio mixing data, code, and identity',           tags: ['identity', 'instagram'],    image: null, featured: false },
  { id: 'hoodzpah',        name: 'Hoodzpah Design',    url: 'https://www.instagram.com/hoodzpahdesign/',  category: 'agency-studio', desc: 'Sister duo with bold, retro-inspired design',             tags: ['type', 'instagram'],        image: null, featured: false, added: '2026-04-27' },
  { id: 'porto-rocha',     name: 'Porto Rocha',        url: 'https://www.instagram.com/porto_rocha/',     category: 'agency-studio', desc: 'Studio redefining sports and street branding',            tags: ['sports', 'instagram'],      image: null, featured: false },
  { id: 'center',          name: 'Center',             url: 'https://www.instagram.com/center/',          category: 'agency-studio', desc: 'Experimental hub for variable type and AI',              tags: ['variable', 'instagram'],    image: null, featured: false },
  { id: 'wolff-olins',     name: 'Wolff Olins',        url: 'https://www.instagram.com/wolffolins/',      category: 'agency-studio', desc: 'Global branding consultancy known for innovation',        tags: ['identity', 'instagram'],    image: null, featured: false },
  { id: 'studio-nari',     name: 'Studio Nari',        url: 'https://www.instagram.com/studionari/',      category: 'agency-studio', desc: 'Madrid studio with editorial and spatial design',         tags: ['editorial', 'instagram'],   image: null, featured: false },
  { id: 'studio-dumbar',   name: 'Studio Dumbar',      url: 'https://www.instagram.com/studiodumbar/',    category: 'agency-studio', desc: 'Dutch studio known for kinetic typography',               tags: ['motion', 'instagram'],      image: null, featured: false, added: '2026-04-27' },
  { id: 'vucko',           name: 'Vucko',              url: 'https://www.instagram.com/vucko.co/',        category: 'agency-studio', desc: 'Story-driven motion branding and animations',             tags: ['motion', 'instagram'],      image: null, featured: false },
  { id: 'dia-studio',      name: 'Dia Studio',         url: 'https://www.instagram.com/dia_studio/',      category: 'agency-studio', desc: 'Data-driven motion identities and experiments',           tags: ['motion', 'instagram'],      image: null, featured: false },

  // ── DESIGNERS ─────────────────────────────────────────────────────────────
  { id: 'god-is-a-designer',     name: 'God Is A Designer',      url: 'https://www.instagram.com/godisadesigner/',       category: 'designers', desc: 'Faith-based streetwear merging scripture graphics',     tags: ['faith', 'instagram'],      image: null, featured: false },
  { id: 'friends-x-family',      name: 'Friends x Family',       url: 'https://www.instagram.com/friendsxfamily_/',      category: 'designers', desc: 'Fashion-forward church merch collective',               tags: ['faith', 'instagram'],      image: null, featured: false },
  { id: 'ruido-98',              name: 'Ruido 98',               url: 'https://www.instagram.com/ruido.98/',             category: 'designers', desc: 'AI art experiments and MidJourney prompts',             tags: ['ai', 'instagram'],         image: null, featured: false },
  { id: 'design-with-dan',       name: 'Design With Dan',        url: 'https://www.instagram.com/designwithdan/',        category: 'designers', desc: 'Sports poster and athlete branding inspiration',         tags: ['sports', 'instagram'],     image: null, featured: false },
  { id: 'japaaron',              name: 'Japaaron',               url: 'https://www.instagram.com/japaaron/',             category: 'designers', desc: 'Moody experimental graphic design content',             tags: ['experimental', 'instagram'],image: null, featured: false },
  { id: 'josh-warner',           name: 'Josh Warner',            url: 'https://www.instagram.com/joshwarner.art/',       category: 'designers', desc: '3D visuals for church media',                           tags: ['3d', 'instagram'],         image: null, featured: false },
  { id: 'sigvard-nilsson',       name: 'Sigvard Nilsson',        url: 'https://www.instagram.com/sigvardnilsson/',       category: 'designers', desc: 'Minimal layouts with scripture-inspired art',            tags: ['minimal', 'instagram'],    image: null, featured: false },
  { id: 'rjv-collectives',       name: 'RJV Collectives',        url: 'https://www.instagram.com/rjv_collectives/',      category: 'designers', desc: 'Mixed-media worship design collective',                  tags: ['faith', 'instagram'],      image: null, featured: false },
  { id: 'clayton-haight',        name: 'Clayton Haight',         url: 'https://www.instagram.com/claytonjhaight/',       category: 'designers', desc: 'Gradient-heavy worship graphics',                        tags: ['faith', 'instagram'],      image: null, featured: false },
  { id: 'kevin-hackett-art',     name: 'Kevin Hackett',          url: 'https://www.instagram.com/kevinhackett.art/',     category: 'designers', desc: 'Album art and stage design for music acts',             tags: ['music', 'instagram'],      image: null, featured: false },
  { id: 'kevin-hackett',         name: 'Kevin Hackett (Process)',url: 'https://www.instagram.com/kevin.hackett/',        category: 'designers', desc: 'Behind-the-scenes design process',                       tags: ['process', 'instagram'],    image: null, featured: false },
  { id: 'magdiel-lopez',         name: 'Magdiel Lopez',          url: 'https://www.instagram.com/magdiellop/',           category: 'designers', desc: 'Surreal collages combining faith and color',             tags: ['collage', 'instagram'],    image: null, featured: false },
  { id: 'mnaum-design',          name: 'Mnaum Design',           url: 'https://www.instagram.com/mnaumanndesign/',       category: 'designers', desc: 'Chrome metal typography and 3D art',                    tags: ['3d', 'instagram'],         image: null, featured: false },
  { id: 'baugasm',               name: 'Baugasm',                url: 'https://www.instagram.com/baugasm/',              category: 'designers', desc: 'Daily gradient poster challenges',                       tags: ['gradients', 'instagram'],  image: null, featured: false },
  { id: 'syyn-studios',          name: 'Syyn Studios',           url: 'https://www.instagram.com/syynstudios/',          category: 'designers', desc: 'Kinetic typography and collage experiments',            tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'no-pattern',            name: 'No Pattern',             url: 'https://www.instagram.com/nopattern/',            category: 'designers', desc: 'Trend-setting gradient-rich poster designs',             tags: ['gradients', 'instagram'],  image: null, featured: false },
  { id: 'jerbosmans',            name: 'Jerbosmans',             url: 'https://www.instagram.com/jerbosmans/',           category: 'designers', desc: 'Layered color studies with bold typography',            tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'medg',                  name: 'Medg',                   url: 'https://www.instagram.com/_medg/',                category: 'designers', desc: 'Psychedelic black-and-white collage art',               tags: ['collage', 'instagram'],    image: null, featured: false },
  { id: 'vasjen-katro',          name: 'Vasjen Katro',           url: 'https://www.instagram.com/vasjenkatro/',          category: 'designers', desc: 'Atmospheric gradient landscapes',                        tags: ['gradients', 'instagram'],  image: null, featured: false },
  { id: 'andrey-azizov',         name: 'Andrey Azizov',          url: 'https://www.instagram.com/andreyazizov/',         category: 'designers', desc: 'Quick Illustrator and Photoshop tips',                   tags: ['tutorials', 'instagram'],  image: null, featured: false },
  { id: 'callums-creative-club', name: "Callum's Creative Club", url: 'https://www.instagram.com/callumscreativeclub/',  category: 'designers', desc: 'Adobe app tips, updates, and workflows',                tags: ['tutorials', 'instagram'],  image: null, featured: false },
  { id: 'type-design-class',     name: 'Type Design Class',      url: 'https://www.instagram.com/typedesignclass/',      category: 'designers', desc: 'Lessons on drawing and spacing custom letters',         tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'morula-type',           name: 'Morula Type',            url: 'https://www.instagram.com/morula_type/',          category: 'designers', desc: 'Modular type specimens and font experiments',           tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'bmnicks',               name: 'Bmnicks',                url: 'https://www.instagram.com/bmnicks/',              category: 'designers', desc: 'Behind-the-scenes glyph sketches and releases',         tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'amtakethat',            name: 'amtakethat',             url: 'https://www.instagram.com/amtakethat/',           category: 'designers', desc: 'Custom wordmarks and branding lockups',                  tags: ['wordmarks', 'instagram'],  image: null, featured: false },
  { id: 'ridding-ink',           name: 'Ridding Ink Design',     url: 'https://www.instagram.com/a13riddinginkdesign/',  category: 'designers', desc: 'Archive of typographic posters',                        tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'brand-identity-ig',     name: 'The Brand Identity',     url: 'https://www.instagram.com/thebrandidentity/',     category: 'designers', desc: 'Global brand identity features',                        tags: ['identity', 'instagram'],   image: null, featured: false },
  { id: 'graphic-addict',        name: 'The Graphic Addict',     url: 'https://www.instagram.com/thegraphicaddict/',     category: 'designers', desc: 'Curated modernist posters and zines',                   tags: ['posters', 'instagram'],    image: null, featured: false },
  { id: 'digital-archive-ig',    name: 'Digital Archive',        url: 'https://www.instagram.com/digital_archive/',      category: 'designers', desc: 'Digitized rare design ephemera and posters',            tags: ['archive', 'instagram'],    image: null, featured: false },
  { id: 'bymonotype',            name: 'Bymonotype',             url: 'https://www.instagram.com/bymonotype/',           category: 'designers', desc: 'Daily type trivia, font facts, foundry news',           tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'type-01',               name: 'Type 01',                url: 'https://www.instagram.com/type01_/',              category: 'designers', desc: 'Type releases, interviews, and insights',               tags: ['type', 'instagram'],       image: null, featured: false },

];
