// ─────────────────────────────────────────────────────────────────────────────
// DESIGN INDEX — Resource Data
// ─────────────────────────────────────────────────────────────────────────────
// ADD a resource  → copy any entry, give it a unique id, fill in the fields.
// FEATURE a card  → set  featured: true  (keep ≤ 5 at once).
// MARK as new     → set  added: 'YYYY-MM-DD'  (shows NEW badge for 30 days).
// ADD thumbnail   → drop  images/{id}.jpg  into the images/ folder. No code changes needed.
// ─────────────────────────────────────────────────────────────────────────────

const CATEGORIES = [
  { id: 'design-inspo',     label: 'Inspo',             badge: 'INSPO', emoji: '⚡' },
  { id: 'type-tools',       label: 'Type Tools',        badge: 'TYPE',  emoji: '🛠️' },
  { id: 'type-marketplace', label: 'Type Shops',        badge: 'MKT',   emoji: '🌐' },
  { id: 'type-foundry',     label: 'Type Foundries',    badge: 'FNDR',  emoji: '🔤' },
  { id: 'assets',           label: 'Assets',            badge: 'KIT',   emoji: '🧰' },
  { id: 'color',            label: 'Color',             badge: 'HUE',   emoji: '🖍️' },
  { id: 'stock',            label: 'Stock',             badge: 'IMG',   emoji: '🖼️' },
  { id: 'design-news',      label: 'News',              badge: 'EDIT',  emoji: '🧠' },
  { id: 'books-titles',     label: 'Books',             badge: 'READ',  emoji: '📚' },
  { id: 'bookstores',       label: 'Bookstores',        badge: 'SHOP',  emoji: '🛒' },
  { id: 'creators',         label: 'Creators',          badge: 'WATCH', emoji: '🎥' },
  { id: 'agency-studio',    label: 'Studios',           badge: 'AGCY',  emoji: '🏢' },
  { id: 'designers',        label: 'Designers',         badge: 'DSGN',  emoji: '🎨' },
];

const RESOURCES = [

  // ── DESIGN INSPO ──────────────────────────────────────────────────────────
  { id: 'visuelle',        name: 'Visuelle',         url: 'https://visuelle.co.uk/?_sft_category=design',        category: 'design-inspo', desc: 'UK archive of sharp editorial and identity projects, updated daily.',          tags: ['editorial', 'identity'],       image: null, featured: false },
  { id: 'visual-journal',  name: 'Visual Journal',   url: 'https://visualjournal.it',                            category: 'design-inspo', desc: 'Curated blog of the finest branding and graphic design worldwide.',            tags: ['branding', 'curated'],         image: null, featured: false },
  { id: 'arena',           name: 'Are.na',           url: 'https://www.are.na',                                  category: 'design-inspo', desc: 'Visual bookmarking for collaborative mood boards and reference archives.',    tags: ['bookmarking', 'moodboards'],   image: null, featured: false },
  { id: 'behance',         name: 'Behance',          url: 'https://www.behance.net/',                            category: 'design-inspo', desc: 'Portfolio network showcasing professional work across all disciplines.',      tags: ['portfolio', 'inspiration'],    image: null, featured: false },
  { id: 'cosmos',          name: 'Cosmos',           url: 'https://cosmos.so',                                   category: 'design-inspo', desc: 'Minimal daily feed of experimental graphics and typography.',                  tags: ['curated', 'editorial'],        image: null, featured: false },
  { id: 'pinterest',       name: 'Pinterest',        url: 'https://pinterest.com',                               category: 'design-inspo', desc: 'Fast image search for palette and composition references.',                    tags: ['reference', 'moodboards'],     image: null, featured: false },
  { id: 'archives-design', name: 'Archives Design',  url: 'https://archives.design',                             category: 'design-inspo', desc: 'Digital archive of graphic design items from the Internet Archive.',           tags: ['archive', 'historical'],       image: null, featured: false },
  { id: 'savee-it',        name: 'Savee It',         url: 'https://savee.it',                                    category: 'design-inspo', desc: 'Grid-based inspiration boards for style-forward imagery.',                     tags: ['bookmarking', 'moodboards'],   image: null, featured: false },

  // ── STOCK ─────────────────────────────────────────────────────────────────
  { id: 'artvee',                name: 'ArtVee',                url: 'https://artvee.com/',                                   category: 'stock', desc: 'Curated public-domain artworks from museums, searchable by artist and era.',   tags: ['fine art', 'public domain'],   image: null, featured: false },
  { id: 'public-work',           name: 'Public.Work',           url: 'https://public.work/',                                  category: 'stock', desc: 'Minimal directory of high-resolution public-domain image archives.',           tags: ['public domain', 'searchable'], image: null, featured: false },
  { id: 'public-domain-archive', name: 'Public Domain Archive', url: 'https://pdimagearchive.org/infinite-view/',             category: 'stock', desc: 'Over 10,000 out-of-copyright historical images, free to reuse.',               tags: ['historical', 'free'],          image: null, featured: false },
  { id: 'unsplash-exp',          name: 'Unsplash Experimental', url: 'https://unsplash.com/t/experimental',                  category: 'stock', desc: 'Curated abstract photography for textures and mood boards.',                    tags: ['abstract', 'photography'],     image: null, featured: false },
  { id: 'pexels',                name: 'Pexels',                url: 'https://www.pexels.com/',                               category: 'stock', desc: 'Free stock photos and videos cleared for commercial use.',                      tags: ['free', 'commercial'],          image: null, featured: false },

  // ── TYPE TOOLS ────────────────────────────────────────────────────────────
  { id: 'font-ninja',  name: 'Font Ninja',   url: 'https://chromewebstore.google.com/detail/fonts-ninja/eljapbgkmlngdpckoiiibecpemleclhh?hl=en-US', category: 'type-tools', desc: 'Browser extension that identifies any website font instantly.',        tags: ['extension', 'fonts'],  image: null, featured: true, featuredOrder: 2 },
  { id: 'font-base',   name: 'Font Base',    url: 'https://fontba.se/',                                                                              category: 'type-tools', desc: 'Free desktop font manager for organizing and previewing local fonts.',   tags: ['fonts', 'manager'],    image: null, featured: false },
  { id: 'typelab',     name: 'TypeLab',      url: 'https://matthewcrtv.gumroad.com/l/typelab',                                                       category: 'type-tools', desc: 'Free high-quality typefaces for web and desktop use.',                  tags: ['free', 'fonts'],       image: null, featured: false },

  // ── TYPE MARKETPLACE ──────────────────────────────────────────────────────
  { id: 'creative-market', name: 'Creative Market',  url: 'https://creativemarket.com/fonts',  category: 'type-marketplace', desc: 'Marketplace for affordable fonts, mockups, and digital assets.',     tags: ['fonts', 'marketplace'],  image: null, featured: false },
  { id: 'pixel-surplus',   name: 'Pixel Surplus',    url: 'https://pixelsurplus.com',          category: 'type-marketplace', desc: 'Affordable bundles of fonts, textures, and creative kits.',          tags: ['bundles', 'fonts'],       image: null, featured: false },
  { id: 'type-department', name: 'Type Department',  url: 'https://type-department.com',       category: 'type-marketplace', desc: 'Marketplace stocking hard-to-find indie foundries worldwide.',       tags: ['indie', 'marketplace'],  image: null, featured: false },

  // ── TYPE FOUNDRY ──────────────────────────────────────────────────────────
  { id: 'blaze-type',         name: 'Blaze Type',             url: 'https://blazetype.eu/',                    category: 'type-foundry', desc: 'Independent foundry with bold contemporary display families.',              tags: ['display', 'foundry'],       image: null, featured: false },
  { id: 'brandon-nickerson',  name: 'Brandon Nickerson',      url: 'https://www.bnicks.com/',                  category: 'type-foundry', desc: 'Premium lettering resources and customizable wordmark templates.',           tags: ['lettering', 'wordmarks'],   image: null, featured: false },
  { id: 'emyself-design',     name: 'Emyself Design',         url: 'https://emyselfdesign.com',                category: 'type-foundry', desc: 'Boutique studio with expressive, texture-rich typefaces.',                  tags: ['expressive', 'display'],    image: null, featured: false },
  { id: 'off-type',           name: 'Off-type',               url: 'https://off-type.com',                     category: 'type-foundry', desc: 'Experimental variable and kinetic fonts.',                                   tags: ['variable', 'kinetic'],      image: null, featured: false },
  { id: 'sharp-type',         name: 'Sharp Type',             url: 'https://www.sharptype.co/',                category: 'type-foundry', desc: 'High-performance retail type trusted by major publishers.',                 tags: ['editorial', 'premium'],     image: null, featured: false },
  { id: 'ohno-type',          name: 'OhNo Type Co',           url: 'https://ohnotype.co/',                     category: 'type-foundry', desc: 'Whimsical yet highly legible display and text font families.',               tags: ['display', 'text'],          image: null, featured: false },
  { id: 'ott-foundry',        name: 'OTT Foundry',            url: 'https://ott-foundry.com/',                 category: 'type-foundry', desc: 'Korean foundry blending tradition with modern grotesques.',                 tags: ['grotesque', 'korean'],      image: null, featured: false },
  { id: 'pangram-pangram',    name: 'Pangram Pangram',        url: 'https://pangrampangram.com',               category: 'type-foundry', desc: 'Free trial fonts for versatile modern branding.',                            tags: ['free', 'branding'],         image: null, featured: false },
  { id: 'tan-type',           name: 'Tan Type Co',            url: 'https://creativemarket.com/tantype',       category: 'type-foundry', desc: 'Elegant fashion-forward display fonts via Creative Market.',                tags: ['fashion', 'display'],       image: null, featured: false },
  { id: 'designers-foundry',  name: 'The Designers Foundry',  url: 'https://www.thedesignersfoundry.com/',    category: 'type-foundry', desc: 'Limited edition releases from international independent type designers.',    tags: ['indie', 'limited'],         image: null, featured: false },
  { id: 'tropical-type',      name: 'Tropical Type',          url: 'https://tropicaltype.com',                 category: 'type-foundry', desc: 'Tropical-inspired lettering for youth and apparel graphics.',               tags: ['display', 'apparel'],       image: null, featured: false },
  { id: 'abc-dinamo',         name: 'ABC Dinamo',             url: 'https://abcdinamo.com/',                   category: 'type-foundry', desc: 'Swiss variable font innovators with playful alternates.',                   tags: ['variable', 'swiss'],        image: null, featured: false },
  { id: 'vj-type',            name: 'VJ Type',                url: 'https://www.vj-type.com',                  category: 'type-foundry', desc: 'Open-source variable fonts for bold editorial use.',                        tags: ['variable', 'open-source'],  image: null, featured: false },

  // ── DESIGN NEWS ───────────────────────────────────────────────────────────
  { id: 'brand-new',          name: 'Brand New',          url: 'https://www.underconsideration.com/brandnew',  category: 'design-news', desc: 'Daily logo and rebrand critiques with sharp professional commentary.',   tags: ['logos', 'critiques'],    image: null, featured: false },
  { id: 'creative-boom',      name: 'Creative Boom',      url: 'https://www.creativeboom.com/',                category: 'design-news', desc: 'Interviews, inspiration, and advice for emerging creatives.',            tags: ['editorial', 'advice'],   image: null, featured: false },
  { id: 'design-reviewed',    name: 'Design Reviewed',    url: 'https://designreviewed.com/',                  category: 'design-news', desc: 'Archive of 20th-century graphic design, advertising, and ephemera.',     tags: ['archive', 'historical'], image: null, featured: false },
  { id: 'its-nice-that',      name: "It's Nice That",     url: 'https://www.itsnicethat.com/',                 category: 'design-news', desc: 'Editorial platform on art, culture, and experimental design.',           tags: ['editorial', 'culture'],  image: null, featured: false },
  { id: 'tldr-design',        name: 'TLDR Design',        url: 'https://tldr.tech/design',                     category: 'design-news', desc: 'Weekly roundup of essential design news and tools.',                     tags: ['newsletter', 'weekly'],  image: null, featured: true, featuredOrder: 4, added: '2026-04-22' },
  { id: 'the-brand-identity', name: 'The Brand Identity', url: 'https://the-brandidentity.com/',               category: 'design-news', desc: 'Deep-dive features on identities and print from top studios.',           tags: ['identity', 'editorial'], image: null, featured: false },

  // ── YOUTUBE CREATORS ──────────────────────────────────────────────────────
  { id: 'design-syndrome-yt', name: 'Design.Syndrome',  url: 'https://www.youtube.com/@design.syndrome',  category: 'creators', desc: 'Process breakdowns and asset packs from an experimental agency.',    tags: ['tutorials', 'assets'],      image: null, featured: false },
  { id: 'doron-studio-yt',    name: 'Doron Studio',     url: 'https://www.youtube.com/@DoronStudio',      category: 'creators', desc: 'Photoshop and illustration tutorials with free resources.',          tags: ['tutorials', 'photoshop'],   image: null, featured: false },
  { id: 'oren-meets-world',   name: 'Oren Meets World', url: 'https://www.youtube.com/@orenmeetsworld',   category: 'creators', desc: 'Freelance vlogs, business advice, and design challenges.',            tags: ['freelance', 'career'],      image: null, featured: false },
  { id: 'piximperfect',       name: 'PiXimperfect',     url: 'https://www.youtube.com/c/PiXimperfect',   category: 'creators', desc: 'Industry-standard Photoshop retouching and compositing techniques.',  tags: ['photoshop', 'tutorials'],   image: null, featured: false },
  { id: 'louis-moss',         name: 'Louis Moss',       url: 'https://www.youtube.com/@LouisMoss',       category: 'creators', desc: 'Concise Illustrator lessons on logos, type, and branding.',           tags: ['illustrator', 'tutorials'], image: null, featured: false },
  { id: 'the-futur',          name: 'The Futur',        url: 'https://www.youtube.com/@thefutur',        category: 'creators', desc: 'Strategy, pricing, and career coaching for professional creatives.',  tags: ['career', 'business'],       image: null, featured: false },

  // ── BOOKS ─────────────────────────────────────────────────────────────────
  { id: 'gd-visionaries', name: 'Graphic Design Visionaries',       url: 'https://www.goodreads.com/book/show/23197685-graphic-design-visionaries?ref=nav_sb_ss_1_45',         category: 'books-titles', desc: 'Profiles of 75 groundbreaking designers with images and process insights.',   tags: ['designers', 'history'],    image: null, featured: false },
  { id: 'grid-systems',   name: 'Grid Systems in Graphic Design',   url: 'https://www.goodreads.com/book/show/60664913-grid-systems-in-graphic-design?utm_source=chatgpt.com', category: 'books-titles', desc: 'The definitive Swiss text on grids, hierarchy, and composition.',             tags: ['grids', 'swiss'],          image: null, featured: false },
  { id: 'herding-tigers', name: 'Herding Tigers',                   url: 'https://www.goodreads.com/book/show/34427197-herding-tigers?ref=nav_sb_ss_1_11',                    category: 'books-titles', desc: 'Leadership guide to managing and motivating creative teams.',                 tags: ['management', 'leadership'],image: null, featured: false },
  { id: 'meggs-history',  name: "Megg's History of Graphic Design", url: 'https://www.goodreads.com/book/show/641593.Meggs_History_of_Graphic_Design?utm_source=chatgpt.com', category: 'books-titles', desc: 'Comprehensive chronology of graphic design movements and milestones.',        tags: ['history', 'reference'],    image: null, featured: false },
  { id: 'gd-history-2',   name: 'History of Graphic Design Vol. 2',url: 'https://www.goodreads.com/book/show/42111600-the-history-of-graphic-design-vol-2-1960-today?ref=nav_sb_ss_2_29',  category: 'books-titles', desc: 'Visual timeline of global design innovation from 1960 to today.',  tags: ['history', 'reference'],    image: null, featured: false },
  { id: 'gd-history-1',   name: 'History of Graphic Design Vol. 1',url: 'https://www.goodreads.com/book/show/37852859-the-history-of-graphic-design-vol-1-1890-1959?ref=nav_sb_ss_1_29',   category: 'books-titles', desc: 'Survey of major movements and landmark works from 1890–1959.',        tags: ['history', 'reference'],    image: null, featured: false },

  // ── BOOKSTORES ────────────────────────────────────────────────────────────
  { id: 'counter-print', name: 'Counter Print UK', url: 'https://www.counter-print.co.uk',  category: 'bookstores', desc: 'Indie UK retailer for modernist books, zines, and magazines.',        tags: ['indie', 'zines'],          image: null, featured: false },
  { id: 'draw-down',     name: 'Draw-Down Books',  url: 'https://www.draw-down.com',         category: 'bookstores', desc: 'Publisher specializing in typography and risograph art books.',       tags: ['typography', 'risograph'], image: null, featured: false },
  { id: 'taschen',       name: 'TASCHEN',           url: 'https://www.taschen.com',           category: 'bookstores', desc: 'Coffee table publisher for lavish art and design monographs.',        tags: ['monographs', 'art'],       image: null, featured: false },
  { id: 'unit-editions', name: 'Unit Editions',    url: 'https://uniteditions.com/',         category: 'bookstores', desc: 'Limited run books from legendary designers and studios.',             tags: ['limited', 'premium'],      image: null, featured: false },
  { id: 'victionary',    name: 'Victionary',        url: 'https://victionary.com',            category: 'bookstores', desc: 'Hong Kong imprint of trend-forward, tactile art books.',              tags: ['art books', 'asia'],       image: null, featured: false },

  // ── ASSETS / RESOURCES ────────────────────────────────────────────────────
  { id: 'tooooools',           name: 'Tooooools',            url: 'https://www.tooooools.app/',                        category: 'assets', desc: 'Free experimental lo-fi effects for online image processing.',       tags: ['free', 'effects'],        image: null, featured: false },
  { id: 'effect-app',          name: 'Effect App',           url: 'https://effect.app',                                category: 'assets', desc: 'Expanded lo-fi and experimental image effects browser tool.',        tags: ['effects', 'tools'],       image: null, featured: false },
  { id: 'blkmarket',           name: 'BlkMarket',            url: 'https://blkmarket.com/',                            category: 'assets', desc: 'Premium textures, overlays, and 3D elements for poster design.',     tags: ['textures', '3d'],         image: null, featured: false },
  { id: 'bracken-design',      name: 'Bracken.design',       url: 'https://www.bracken.design/',                       category: 'assets', desc: 'High-fidelity grunge brushes and torn paper mockups.',              tags: ['grunge', 'brushes'],      image: null, featured: false },
  { id: 'foxrockettstudio',    name: 'Foxrockettstudio',     url: 'https://foxrockettstudio.com/collections/assets',  category: 'assets', desc: 'Creative asset packs and graphic design resources.',                 tags: ['assets', 'kits'],         image: null, featured: false },
  { id: 'design-family-mkt',   name: 'Design Family Market', url: 'https://www.designfamilymarket.com/',               category: 'assets', desc: 'Discounted bundles of fonts, textures, and Photoshop LUTs.',        tags: ['bundles', 'photoshop'],   image: null, featured: false },
  { id: 'design-syndrome',     name: 'Design Syndrome',      url: 'https://designsyndrome.com/',                       category: 'assets', desc: 'Poster templates, gradient assets, and unique graphic kits.',        tags: ['templates', 'kits'],      image: null, featured: false },
  { id: 'doron-supply',        name: 'Doron Supply',         url: 'https://doronsupply.com',                           category: 'assets', desc: 'Photo and video overlays from a multidisciplinary creator.',        tags: ['overlays', 'video'],      image: null, featured: true, featuredOrder: 5 },
  { id: 'samolevsky',          name: 'Samolevsky',           url: 'https://samolevsky.com',                            category: 'assets', desc: 'Glitch textures, brushes, and retro graphic kits.',                 tags: ['glitch', 'textures'],     image: null, featured: false },
  { id: 'studio-2am',          name: 'Studio 2AM',           url: 'https://studio2am.co',                              category: 'assets', desc: 'High-resolution collage elements and poster templates.',            tags: ['collage', 'templates'],   image: null, featured: false },
  { id: 'studio-aaa',          name: 'Studio AAA',           url: 'https://studioaaa.com',                             category: 'assets', desc: 'Cinematic mockups and Lightroom presets with dark aesthetics.',      tags: ['mockups', 'presets'],     image: null, featured: false },
  { id: 'studio-innate',       name: 'Studio Innate',        url: 'https://shop.studioinnate.com',                     category: 'assets', desc: 'Gradients, grids, and experimental textures for dark designs.',     tags: ['gradients', 'textures'],  image: null, featured: false },
  { id: 'true-grit',           name: 'True Grit Texture Supply', url: 'https://truegrittexturesupply.com',             category: 'assets', desc: 'Distressed brushes and craft texture packs for indie aesthetics.',  tags: ['textures', 'brushes'],    image: null, featured: false },
  { id: 'youworkforthem',      name: 'YouWorkForThem',       url: 'https://youworkforthem.com',                        category: 'assets', desc: 'Premium marketplace for fonts, graphics, and motion templates.',     tags: ['fonts', 'premium'],       image: null, featured: false },

  // ── COLOR ─────────────────────────────────────────────────────────────────
  { id: 'coolors',               name: 'Coolors',               url: 'https://coolors.co/',                   category: 'color', desc: 'AI-powered palette generator with export-ready codes.',         tags: ['palette', 'generator'], image: null, featured: false },
  { id: 'color-hunt',            name: 'Color Hunt',            url: 'https://colorhunt.co/',                 category: 'color', desc: 'Community-curated palettes sorted by theme and mood.',          tags: ['palette', 'community'], image: null, featured: false },
  { id: 'adobe-color',           name: 'Adobe Color',           url: 'https://color.adobe.com',               category: 'color', desc: 'Palette harmonies and trend analytics for Adobe apps.',         tags: ['adobe', 'palette'],     image: null, featured: false },
  { id: 'pigment-shape-factory', name: 'Pigment Shape Factory', url: 'https://pigment.shapefactory.co/',      category: 'color', desc: 'Modern gradient and duotone scheme generator.',                 tags: ['gradient', 'duotone'],  image: null, featured: true, featuredOrder: 3 },
  { id: 'khroma',                name: 'Khroma',                url: 'https://www.khroma.co',                 category: 'color', desc: 'AI that learns your taste and predicts matching palettes.',     tags: ['ai', 'palette'],        image: null, featured: false },

  // ── AGENCY / STUDIO ───────────────────────────────────────────────────────
  { id: 'studio-koto',     name: 'Studio Koto',       url: 'https://www.instagram.com/studiokoto/',        category: 'agency-studio', desc: 'London studio sharing brand systems and cultural projects.',             tags: ['branding', 'instagram'],    image: null, featured: true, featuredOrder: 1, added: '2026-04-22' },
  { id: 'and-walsh',       name: 'And Walsh',          url: 'https://www.instagram.com/andwalsh/',          category: 'agency-studio', desc: 'Campaign case studies from Sagmeister & Walsh.',                         tags: ['campaigns', 'instagram'],   image: null, featured: false },
  { id: 'studio-feixen',   name: 'Studio Feixen',      url: 'https://www.instagram.com/studiofeixen/',     category: 'agency-studio', desc: 'Swiss studio with playful color blocking and motion experiments.',       tags: ['motion', 'instagram'],      image: null, featured: false },
  { id: 'the-new-company', name: 'The New Company',    url: 'https://www.instagram.com/thenewcompany/',    category: 'agency-studio', desc: 'NYC studio with minimalist identities and sharp typography.',            tags: ['identity', 'instagram'],    image: null, featured: false },
  { id: 'this-is-collins', name: 'This Is Collins',    url: 'https://www.instagram.com/thisiscollins/',    category: 'agency-studio', desc: 'Culture-driven rebrands and dynamic design systems.',                   tags: ['branding', 'instagram'],    image: null, featured: false },
  { id: 'wieden-kennedy',  name: 'Wieden Kennedy',     url: 'https://www.instagram.com/wiedenkennedy/',   category: 'agency-studio', desc: 'Global ad agency known for iconic storytelling campaigns.',              tags: ['advertising', 'instagram'], image: null, featured: false },
  { id: 'design-studio',   name: 'Design Studio',      url: 'https://www.instagram.com/__designstudio__/',category: 'agency-studio', desc: 'London studio mixing data, code, and striking visual identities.',       tags: ['identity', 'instagram'],    image: null, featured: false },
  { id: 'hoodzpah',        name: 'Hoodzpah Design',    url: 'https://www.instagram.com/hoodzpahdesign/',  category: 'agency-studio', desc: 'Sisters duo sharing bold type, retro vibes, and process tips.',         tags: ['type', 'instagram'],        image: null, featured: false },
  { id: 'porto-rocha',     name: 'Porto Rocha',        url: 'https://www.instagram.com/porto_rocha/',     category: 'agency-studio', desc: 'Studio redefining sports and street culture graphics.',                 tags: ['sports', 'instagram'],      image: null, featured: false },
  { id: 'center',          name: 'Center',             url: 'https://www.instagram.com/center/',          category: 'agency-studio', desc: 'Experimental hub for variable type and AI-assisted branding.',          tags: ['variable', 'instagram'],    image: null, featured: false },
  { id: 'wolff-olins',     name: 'Wolff Olins',        url: 'https://www.instagram.com/wolffolins/',      category: 'agency-studio', desc: 'Heritage consultancy sharing future-proof identity work.',              tags: ['identity', 'instagram'],    image: null, featured: false },
  { id: 'studio-nari',     name: 'Studio Nari',        url: 'https://www.instagram.com/studionari/',      category: 'agency-studio', desc: 'Madrid studio with hybrid editorial and spatial design.',               tags: ['editorial', 'instagram'],   image: null, featured: false },
  { id: 'studio-dumbar',   name: 'Studio Dumbar',      url: 'https://www.instagram.com/studiodumbar/',    category: 'agency-studio', desc: 'Dutch motion shop known for kinetic typographic work.',                 tags: ['motion', 'instagram'],      image: null, featured: false },
  { id: 'vucko',           name: 'Vucko',              url: 'https://www.instagram.com/vucko.co/',        category: 'agency-studio', desc: 'Story-driven motion studies and brand launch animations.',              tags: ['motion', 'instagram'],      image: null, featured: false },
  { id: 'dia-studio',      name: 'Dia Studio',         url: 'https://www.instagram.com/dia_studio/',      category: 'agency-studio', desc: 'Data-led motion identities and algorithmic design experiments.',        tags: ['motion', 'instagram'],      image: null, featured: false },

  // ── DESIGNERS ─────────────────────────────────────────────────────────────
  { id: 'god-is-a-designer',     name: 'God Is A Designer',      url: 'https://www.instagram.com/godisadesigner/',       category: 'designers', desc: 'Christian streetwear merging scripture with modern graphics.',          tags: ['faith', 'instagram'],      image: null, featured: false },
  { id: 'friends-x-family',      name: 'Friends x Family',       url: 'https://www.instagram.com/friendsxfamily_/',      category: 'designers', desc: 'Miami church collective dropping fashion-grade merch.',                 tags: ['faith', 'instagram'],      image: null, featured: false },
  { id: 'ruido-98',              name: 'Ruido 98',               url: 'https://www.instagram.com/ruido.98/',             category: 'designers', desc: 'MidJourney prompts, AI tips, and experimental visuals.',               tags: ['ai', 'instagram'],         image: null, featured: false },
  { id: 'design-with-dan',       name: 'Design With Dan',        url: 'https://www.instagram.com/designwithdan/',        category: 'designers', desc: 'NBA-style posters and athlete branding inspiration.',                   tags: ['sports', 'instagram'],     image: null, featured: false },
  { id: 'japaaron',              name: 'Japaaron',               url: 'https://www.instagram.com/japaaron/',             category: 'designers', desc: 'Moody experimental visuals and design-forward creative content.',       tags: ['experimental', 'instagram'],image: null, featured: false },
  { id: 'josh-warner',           name: 'Josh Warner',            url: 'https://www.instagram.com/joshwarner.art/',       category: 'designers', desc: '3D cross-themed renders and sermon series visuals.',                   tags: ['3d', 'instagram'],         image: null, featured: false },
  { id: 'sigvard-nilsson',       name: 'Sigvard Nilsson',        url: 'https://www.instagram.com/sigvardnilsson/',       category: 'designers', desc: 'Scandinavian minimal layouts with scripture-inspired art.',             tags: ['minimal', 'instagram'],    image: null, featured: false },
  { id: 'rjv-collectives',       name: 'RJV Collectives',        url: 'https://www.instagram.com/rjv_collectives/',      category: 'designers', desc: 'Mixed media worship visuals from a curated collective.',               tags: ['faith', 'instagram'],      image: null, featured: false },
  { id: 'clayton-haight',        name: 'Clayton Haight',         url: 'https://www.instagram.com/claytonjhaight/',       category: 'designers', desc: 'Gradient-heavy experimental graphics for church media.',               tags: ['faith', 'instagram'],      image: null, featured: false },
  { id: 'kevin-hackett-art',     name: 'Kevin Hackett',          url: 'https://www.instagram.com/kevinhackett.art/',     category: 'designers', desc: 'Album art, merch, and stage visuals for Reach Records.',               tags: ['music', 'instagram'],      image: null, featured: false },
  { id: 'kevin-hackett',         name: 'Kevin Hackett (Process)',url: 'https://www.instagram.com/kevin.hackett/',        category: 'designers', desc: 'Behind-the-scenes personal process feed from the same creator.',       tags: ['process', 'instagram'],    image: null, featured: false },
  { id: 'magdiel-lopez',         name: 'Magdiel Lopez',          url: 'https://www.instagram.com/magdiellop/',           category: 'designers', desc: 'Surreal photo collages with bold color and faith imagery.',             tags: ['collage', 'instagram'],    image: null, featured: false },
  { id: 'mnaum-design',          name: 'Mnaum Design',           url: 'https://www.instagram.com/mnaumanndesign/',       category: 'designers', desc: 'Chrome metal typography and abstract 3D renders.',                     tags: ['3d', 'instagram'],         image: null, featured: false },
  { id: 'baugasm',               name: 'Baugasm',                url: 'https://www.instagram.com/baugasm/',              category: 'designers', desc: 'Daily gradient poster challenges and Photoshop tutorials.',             tags: ['gradients', 'instagram'],  image: null, featured: false },
  { id: 'syyn-studios',          name: 'Syyn Studios',           url: 'https://www.instagram.com/syynstudios/',          category: 'designers', desc: 'Variable font collages, kinetic type, and layout experiments.',         tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'no-pattern',            name: 'No Pattern',             url: 'https://www.instagram.com/nopattern/',            category: 'designers', desc: 'Trend-setting gradient-rich posters and merchandise.',                 tags: ['gradients', 'instagram'],  image: null, featured: false },
  { id: 'jerbosmans',            name: 'Jerbosmans',             url: 'https://www.instagram.com/jerbosmans/',           category: 'designers', desc: 'Layered color studies and bold typographic lockups.',                   tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'medg',                  name: 'Medg',                   url: 'https://www.instagram.com/_medg/',                category: 'designers', desc: 'Black-and-white collage fused with psychedelic textures.',             tags: ['collage', 'instagram'],    image: null, featured: false },
  { id: 'vasjen-katro',          name: 'Vasjen Katro',           url: 'https://www.instagram.com/vasjenkatro/',          category: 'designers', desc: 'Gradient studies and ambient abstract landscapes.',                     tags: ['gradients', 'instagram'],  image: null, featured: false },
  { id: 'andrey-azizov',         name: 'Andrey Azizov',          url: 'https://www.instagram.com/andreyazizov/',         category: 'designers', desc: 'Snappy Illustrator and Photoshop mini lessons.',                       tags: ['tutorials', 'instagram'],  image: null, featured: false },
  { id: 'callums-creative-club', name: "Callum's Creative Club", url: 'https://www.instagram.com/callumscreativeclub/',  category: 'designers', desc: 'Adobe software updates, workflow tips, and challenges.',               tags: ['tutorials', 'instagram'],  image: null, featured: false },
  { id: 'type-design-class',     name: 'Type Design Class',      url: 'https://www.instagram.com/typedesignclass/',      category: 'designers', desc: 'Formal instruction on drawing and spacing custom letterforms.',         tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'morula-type',           name: 'Morula Type',            url: 'https://www.instagram.com/morula_type/',          category: 'designers', desc: 'Modular type specimen explorations and font development.',             tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'bmnicks',               name: 'Bmnicks',                url: 'https://www.instagram.com/bmnicks/',              category: 'designers', desc: 'Behind-the-scenes glyph sketches and type releases.',                 tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'amtakethat',            name: 'amtakethat',             url: 'https://www.instagram.com/amtakethat/',           category: 'designers', desc: 'Custom wordmark explorations and sports branding lockups.',            tags: ['wordmarks', 'instagram'],  image: null, featured: false },
  { id: 'ridding-ink',           name: 'Ridding Ink Design',     url: 'https://www.instagram.com/a13riddinginkdesign/',  category: 'designers', desc: 'Archived typographic posters for study and reference.',               tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'brand-identity-ig',     name: 'The Brand Identity',     url: 'https://www.instagram.com/thebrandidentity/',     category: 'designers', desc: 'Global identity features, print layouts, and designer interviews.',    tags: ['identity', 'instagram'],   image: null, featured: false },
  { id: 'graphic-addict',        name: 'The Graphic Addict',     url: 'https://www.instagram.com/thegraphicaddict/',     category: 'designers', desc: 'Curated modernist posters and risograph zines.',                       tags: ['posters', 'instagram'],    image: null, featured: false },
  { id: 'digital-archive-ig',    name: 'Digital Archive',        url: 'https://www.instagram.com/digital_archive/',      category: 'designers', desc: 'Digitized rare design ephemera and historical posters.',              tags: ['archive', 'instagram'],    image: null, featured: false },
  { id: 'bymonotype',            name: 'Bymonotype',             url: 'https://www.instagram.com/bymonotype/',           category: 'designers', desc: 'Daily typographic trivia, font facts, and foundry news.',             tags: ['type', 'instagram'],       image: null, featured: false },
  { id: 'type-01',               name: 'Type 01',                url: 'https://www.instagram.com/type01_/',              category: 'designers', desc: 'Font releases, interviews, and type industry insights.',              tags: ['type', 'instagram'],       image: null, featured: false },

];
